export const ON_CHANGE_INPUT_EVENT = 'ON_CHANGE_INPUT_EVENT';
export const ON_CLICK_EVENT_SAVE = 'ON_CLICK_EVENT_SAVE';

export const SAVE_EVENT = 'SAVE_EVENT';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_FAILURE = 'SAVE_EVENT_FAILURE';

export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAILURE = 'SAVE_PRODUCT_FAILURE';

export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE';

export const ON_MODIFY_EVENT = 'ON_MODIFY_EVENT';
export const ON_UPDATE_EVENT = 'ON_UPDATE_EVENT';

export const ON_CHANGE_INPUT_PRODUCT = 'ON_CHANGE_INPUT_PRODUCT';

export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const EVENT_ATTENDANCE_UPDATE = 'EVENT_ATTENDANCE_UPDATE';
export const EVENT_ATTENDANCE_UPDATE_SUCCESS = 'EVENT_ATTENDANCE_UPDATE_SUCCESS';
export const EVENT_ATTENDANCE_UPDATE_FAILURE = 'EVENT_ATTENDANCE_UPDATE_FAILURE';

export const EVENT_DELETE = 'EVENT_DELETE';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAILURE = 'EVENT_DELETE_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
