export const ON_CHANGE_INPUT_PERSON = 'ON_CHANGE_INPUT_PERSON';
export const ON_CHANGE_PERSON_GROUP = 'ON_CHANGE_PERSON_GROUP';

export const ON_CLICK_SAVE = 'ON_CLICK_SAVE';

export const SAVE_PERSON = 'SAVE_PERSON';
export const SAVE_PERSON_SUCCESS = 'SAVE_PERSON_SUCCESS';
export const SAVE_PERSON_FAILURE = 'SAVE_PERSON_FAILURE';

export const PERSON_LIST = 'PERSON_LIST';
export const PERSON_LIST_SUCCESS = 'PERSON_LIST_SUCCESS';
export const PERSON_LIST_FAILURE = 'PERSON_LIST_FAILURE';

export const PERSON_DELETE = 'PERSON_DELETE';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
export const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';

// 이벤트 등록에서 이벤트 참여 인원을 클릭했을 때
export const ON_CLICK_PERSON = 'ON_CLICK_PERSON';
// 이벤트 등록에서 저장을 눌렀을 때
export const INIT_PERSON_ATTENDANCE = 'INIT_PERSON_ATTENDANCE';

export const PERSON_INIT_COUNT = 'PERSON_INIT_COUNT';
export const PERSON_INIT_COUNT_SUCCESS = 'PERSON_INIT_COUNT_SUCCESS';
export const PERSON_INIT_COUNT_FAILURE = 'PERSON_INIT_COUNT_FAILURE';

export const PERSON_INFO = 'PERSON_INFO';
export const PERSON_INFO_SUCCESS = 'PERSON_INFO_SUCCESS';
export const PERSON_INFO_FAILURE = 'PERSON_INFO_FAILURE';

export const ON_MODAL_SHOW = 'ON_MODAL_SHOW';
export const ON_MODAL_HIDE = 'ON_MODAL_HIDE';

export const ON_CHANGE_POINT_USE = 'ON_CHANGE_POINT_USE';
export const ON_FOCUS_POINT_USE = 'ON_FOCUS_POINT_USE';

export const USE_POINT = 'USE_POINT';
export const USE_POINT_SUCCESS = 'USE_POINT_SUCCESS';
export const USE_POINT_FAILURE = 'USE_POINT_FAILURE';